### ISSUE TITLE
Wind speed miles to kms

### ISSUE THREAD

**Issue by darcemac** [michael-lynch/open-weather#5]
Hi Michael, 

Excellent app by the way, using it in a website project and works perfectly and looks great!

I have a question about whether its possible to convert the wind speed from miles to kms and not being fluent in javascript, was wondering if you could help me out please?

Regards,
Darcy

**Comment by michael-lynch** [comment]
I was just about to update the plugin when I noticed that the original wind speed unit isn't miles per hour (mph). It's actually meters per second (mps), so I've updated the unit to read "Mps" instead of "Mph."
